# Generated by Django 3.0.8 on 2021-07-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('pricing', models.FloatField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.CharField(blank=True, choices=[('Construction', 'construction'), ('Teaching', 'teaching'), ('Farming', 'farming'), ('Beauty', 'beauty'), ('Enginering', 'enginering'), ('Business', 'business')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Embu', 'Embu'), ('Kisumu', 'Kisumu'), ('Lodwar', 'Lodwar'), ('Kiambu', 'Kiambu'), ('Vihiga', 'Vihiga'), ('Eldoret', 'Eldoret')], max_length=100, null=True)),
                ('experience', models.CharField(blank=True, choices=[('1 year', '1 year'), ('4 years', '4 years'), ('7 years', '7 years'), ('10 years', '10 years')], max_length=50, null=True)),
            ],
        ),
    ]
